controllers:
  - name: "products"
    db_name: "inventory"
    table_name: "products"
    columns: ["id", "name", "category", "price", "stock"]
    valid_categories: ["Elektronik", "Moda", "Ev & Yaşam", "Spor", "Otomotiv"]
    stock_threshold: 4000
  # More controllers can be added here
  # - name: "users"
  #   db_name: "users"
  #   table_name: "users"
  #   columns: ["id", "name", "age"]
  #   age_threshold: 18
  #   # More options can be added here
